server:
  port: 8084

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/secondstore?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

app:
  appId: 2021000121686534
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDBZooQSDg1NWLZYepXHmmiVLfh4WRalcfwY76UifU6J6OxjhPvxwgquj0y8tPfkG/LaOkcSXkPdK0rnJKGrs17bpBnNA1tp0tOU5Nlfhbcsf7ZAMquQ1PjWmQjSZGSNnS0BngNhNK+MMUR7XfuSNEPo8Dqf8K7D3Aivc6lSg8PaaecGaCoYPNlqValT7UbVhFU+crqF4CKGKqzLKJJOgEvPH8X9pPAHvLbU8gBevrXt9FHeTSyTRVnln7TPywkJQqIEdO99Ite7C8dyyprAVN+h1vdUjtz8dEdSf4z+Z2059YJkYwEQMbAn1D6v/TL88NYgaOqDY0iCJ7IL9KZgdqLAgMBAAECggEAfPp1d+YjpIbWVSIIXLoDi2px1d9giYVHSlo6uySXuzgIeWIWEhotdecaS0VOk6d0Bx/JnIUCXXGJwqgQrEZj9ULSwE6L6vN0H660jp63yXCg/rybPZe2qzIrif4tuy3Dpt6TUDEoOs2rXFV37h1SNGge76sWPOnSDjFYS8obB1qe2ljpwFM+sbWtymCBReFhWGqmTbIJIQRGhit354gosn8AhgYYsjh7L6NKO3Axi8mK/0uzbvrMmq+C5wyKFas87xq9FgC8fz0cVpS4EvydAWlMN2UYXlDQrR6P4yGvk0N93i8oHJZuuU9/R9dUsYjaH78gY3Z06OJtJ6D54DIhSQKBgQD6uNAjRx2pyp4HhFUo1jidFLS6/qydur13RHvKsgVhnd1o0kFcVOCvqrcRs0/dniHVAuv7cItUDXoOhkG89RyQ0+vTpTk3Tvbtd0BPryU4hAP6fodbyehY9L3m11K3vfp8VUPajaPAaZjvzTiCAoixMtgSY4wboZo8ZCab0GgWTwKBgQDFeM+K/0vK1gUwVjBIFUwfwMx4wElQjTTYCJPNiEAjGmOScugUFeozvSYoZSLCrNWBMTLCjwA9+RxZufMPjhKDFUJFODUrNladg5j3A0eyB6u0+gf4GDBX0EAjqKL9OApdQShOCQZ8MgemxlR1Osu41S5yoZOLiMPLx7f878AlBQKBgQDz3M6VgZZYj7sllJFAJxzprDodp5g90mR2nSXLAVw6llHEorzwEZ55PpLRpJcJ98TwauccqVrbZkBR4EQQhlhChd3a/dmo8iU608K5vqF1VvKHson1vW1BGMucu9K45Q+93zEgYqPjgtI+bF2KFuzdbZa8TBb6yTQ7iS4EX7DeAQKBgQCMtqXNulXb194ir4gAFY0FI3GQqhSUHcsGFjacQvbRDMDfXpoZlfQpoiNKraazak1JnjE5ioT1pEmbdnHJJ8fxOHjcskzQ2gumelvJyMCSD/0/HNwI4dOw/2h1AHoETqa0BPYfhTbl0RC6uqD8WEVLFD3g2Vo2F+LNlyd4Sa91sQKBgE/hXRWpGrqzFUox+xR0UgaDYmwBWXkdoTc/vfRlwvMpuWYnPBmst5rJ6w1tfNlnp2ypgMjKedxU2a8WzTToHGpBnKrqwn9moVk08tBx8PKnEvtlFkDNAAuEia2OiyFAK30o9kLoP5PH/PQVdNfK+wTrbwbZOtL9XW6DmML+xtj5
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnHGcwhYqavi6BkT2WFGubRctLhgD7DRkOuT8EZnTaIniteVikLLsKryF41f3YMGSZseUI2zXxJp0xMkUgLK+cI8pN+JliA5KldsWzz5QlV65er0kHHOH8uNXKku9d+EPiih0YC3RvXvIJGwb0aAe8ZfYypzPcOqZRKCFnTFhqhhMRihnKWhAmXV5xFGDNpsBz7XpEFUxQsFhlR4+tIFfB2LGoGFoImF/lEsWwd5zU2F2CTweR4oxZdCq9lvUW3Jh/nDsI+aDAmKEMLXqNa6Mhme/TZHSiTMqIIC/d8MCnjZOqTQvzgDED0/UQjdLPnRYi6uO90wYJP4JmxobzvXGRQIDAQAB
  notifyUrl: http://localhost:8084/ali/success
  returnUrl: http://localhost:8084/ali/success
  signType: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do